export interface Product {
  id: number;
  slug: string;
  name: string;
  category: 'fruit' | 'vegetable' | 'leafy';
  price: number;
  originalPrice: number;
  discount: number;
  sizes: string[];
  image: string;
  description: string;
  benefits: string[];
  fssai: boolean;
  featured?: boolean;
}

export const products: Product[] = [
  {
    id: 1,
    slug: 'beetroot-powder',
    name: 'Beetroot Powder',
    category: 'vegetable',
    price: 238,
    originalPrice: 280,
    discount: 15,
    sizes: ['50g', '150g', '250g'],
    image: '/products/beetroot.jpg',
    description: 'Made from carefully selected fresh raw materials and processed with utmost care to retain all nutrients.',
    benefits: ['Rich in antioxidants', 'Supports heart health', 'Boosts stamina', 'Natural blood pressure support'],
    fssai: true,
    featured: true,
  },
  {
    id: 2,
    slug: 'moringa-powder',
    name: 'Moringa Powder',
    category: 'leafy',
    price: 229,
    originalPrice: 270,
    discount: 15,
    sizes: ['50g', '150g', '250g'],
    image: '/products/moringa.jpg',
    description: 'Premium organic moringa powder packed with essential vitamins and minerals.',
    benefits: ['Nutrient-rich superfood', 'Boosts immunity', 'Natural energy enhancer', 'Anti-inflammatory properties'],
    fssai: true,
    featured: true,
  },
  {
    id: 3,
    slug: 'turmeric-powder',
    name: 'Turmeric Powder',
    category: 'vegetable',
    price: 189,
    originalPrice: 220,
    discount: 14,
    sizes: ['100g', '250g', '500g'],
    image: '/products/turmeric.jpg',
    description: 'Pure turmeric powder with high curcumin content. No additives, no preservatives.',
    benefits: ['Anti-inflammatory', 'Immune support', 'Joint health', 'Natural antioxidant'],
    fssai: true,
    featured: true,
  },
  {
    id: 4,
    slug: 'amla-powder',
    name: 'Amla Powder',
    category: 'fruit',
    price: 199,
    originalPrice: 240,
    discount: 17,
    sizes: ['100g', '200g', '400g'],
    image: '/products/amla.jpg',
    description: 'Rich in Vitamin C, made from sun-dried Indian gooseberries.',
    benefits: ['Vitamin C powerhouse', 'Hair and skin health', 'Digestive support', 'Immunity booster'],
    fssai: true,
    featured: true,
  },
  {
    id: 5,
    slug: 'spinach-powder',
    name: 'Spinach Powder',
    category: 'leafy',
    price: 249,
    originalPrice: 290,
    discount: 14,
    sizes: ['50g', '150g', '300g'],
    image: '/products/spinach.jpg',
    description: 'Nutrient-dense spinach powder, perfect for smoothies and cooking.',
    benefits: ['Iron-rich', 'Bone health', 'Energy booster', 'Antioxidant support'],
    fssai: true,
  },
  {
    id: 6,
    slug: 'carrot-powder',
    name: 'Carrot Powder',
    category: 'vegetable',
    price: 219,
    originalPrice: 260,
    discount: 16,
    sizes: ['100g', '200g', '350g'],
    image: '/products/carrot.jpg',
    description: 'Sweet and versatile carrot powder rich in beta-carotene.',
    benefits: ['Eye health', 'Skin glow', 'Vitamin A source', 'Immune support'],
    fssai: true,
  },
  {
    id: 7,
    slug: 'ginger-powder',
    name: 'Ginger Powder',
    category: 'vegetable',
    price: 169,
    originalPrice: 200,
    discount: 15,
    sizes: ['50g', '100g', '200g'],
    image: '/products/ginger.jpg',
    description: 'Sharp, aromatic ginger powder for wellness and cooking.',
    benefits: ['Digestive aid', 'Anti-nausea', 'Anti-inflammatory', 'Metabolism boost'],
    fssai: true,
  },
  {
    id: 8,
    slug: 'ashwagandha-powder',
    name: 'Ashwagandha Powder',
    category: 'vegetable',
    price: 299,
    originalPrice: 350,
    discount: 14,
    sizes: ['100g', '200g', '400g'],
    image: '/products/ashwagandha.jpg',
    description: 'Premium ashwagandha root powder for stress relief and vitality.',
    benefits: ['Stress reducer', 'Energy booster', 'Sleep support', 'Cognitive health'],
    fssai: true,
  },
  {
    id: 9,
    slug: 'broccoli-powder',
    name: 'Broccoli Powder',
    category: 'vegetable',
    price: 279,
    originalPrice: 330,
    discount: 15,
    sizes: ['50g', '150g', '250g'],
    image: '/products/broccoli.jpg',
    description: 'Concentrated broccoli powder packed with nutrients.',
    benefits: ['Detox support', 'Rich in fiber', 'Vitamin K source', 'Antioxidant power'],
    fssai: true,
  },
  {
    id: 10,
    slug: 'wheatgrass-powder',
    name: 'Wheatgrass Powder',
    category: 'leafy',
    price: 259,
    originalPrice: 300,
    discount: 13,
    sizes: ['100g', '200g', '400g'],
    image: '/products/wheatgrass.jpg',
    description: 'Fresh, green wheatgrass powder for daily nutrition.',
    benefits: ['Chlorophyll-rich', 'Alkalizing', 'Energy boost', 'Detoxification'],
    fssai: true,
  },
  {
    id: 11,
    slug: 'pomegranate-powder',
    name: 'Pomegranate Powder',
    category: 'fruit',
    price: 329,
    originalPrice: 390,
    discount: 15,
    sizes: ['100g', '200g', '300g'],
    image: '/products/pomegranate.jpg',
    description: 'Tangy pomegranate powder rich in antioxidants.',
    benefits: ['Heart health', 'Anti-aging', 'Blood sugar support', 'High antioxidants'],
    fssai: true,
  },
  {
    id: 12,
    slug: 'tomato-powder',
    name: 'Tomato Powder',
    category: 'vegetable',
    price: 199,
    originalPrice: 230,
    discount: 13,
    sizes: ['100g', '250g', '500g'],
    image: '/products/tomato.jpg',
    description: 'Rich tomato powder perfect for soups, sauces, and cooking.',
    benefits: ['Lycopene source', 'Skin health', 'Heart support', 'Vitamin C'],
    fssai: true,
  },
];

export const getFeaturedProducts = () => products.filter(p => p.featured);
export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
export const getProductsByCategory = (category: string) => 
  category === 'all' ? products : products.filter(p => p.category === category);
